#!/bin/sh

/*
Create Config.xcconfig from enviroment variables provided to XCode Cloud
*/
echo "
DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM
BUNDLE_ID_PREFIX = $BUNDLE_ID_PREFIX
BUNDLE_ID_BASE = $BUNDLE_ID_BASE
BASE_URL = $BASE_URL
SUPABASE_URL = $SUPABASE_URL
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
PRIVACY_POLICY_URL = $PRIVACY_POLICY_URL
DEEP_LINK_BASE_URL = $DEEP_LINK_BASE_URL
FEEDBACK_EMAIL = $FEEDBACK_EMAIL
IS_DEBUG = $IS_DEBUG
GIDClientID = $GIDClientID
GIDServerClientID = $GIDServerClientID
GURL = $GURL
" > ../Config.xcconfig
