opt_in_rules:
  - force_unwrapping
  - empty_count
  - trailing_newline
  - colon
  - comma
  - duplicate_imports
  - fatal_error_message
  - first_where
  - weak_delegate
  - void_return
  - fallthrough
  - yoda_condition
  - sorted_imports
  - sorted_first_last
  - identical_operands
  - file_name_no_space
  - empty_string
  - discouraged_none_name
  - contains_over_first_not_nil
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - implicit_return
  - implicitly_unwrapped_optional
  - redundant_type_annotation
  - private_over_fileprivate
  - redundant_nil_coalescing
  - joined_default_parameter
  - explicit_init
  - enum_case_associated_values_count
  - convenience_type
  - legacy_multiple
  - toggle_bool
  - discouraged_object_literal
  - flatmap_over_map_reduce
  - untyped_error_in_catch
  - operator_usage_whitespace
  - optional_enum_case_matching
  - modifier_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - overridden_super_call
  - prohibited_super_call
  - prefer_zero_over_explicit_init
  - static_operator
  - unneeded_parentheses_in_closure_argument
  - last_where
  - closure_end_indentation
  - closure_spacing
  - empty_xctest_method
  - function_default_parameter_at_end
  - pattern_matching_keywords
  - single_test_class
disabled_rules:
  - opening_brace
  - nesting
  - cyclomatic_complexity
  - legacy_random
  - large_tuple
line_length:
  - 140
  - 200
type_body_length:
  - 600
  - 800
function_body_length:
  - 160
  - 240
file_length:
  warning: 500
  error: 800
type_name:
  min_length: 3
identifier_name:
  max_length:
    warning: 45
    error: 50
  min_length:
    warning: 1

private_over_fileprivate:
  validate_extensions: true
  severity: error

force_unwrapping:
  severity: error

redundant_type_annotation: error

excluded:
  - .build
