import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { Navbar, Page } from "konsta/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const supabaseClient = useSupabaseClient();
  const router = useRouter()
  const query = router.query

  console.log(query)
  useEffect(() => {
    const { data: listener } = supabaseClient.auth.onAuthStateChange(
      (event, session) => {
        console.log(session)
        console.log(event);
      }
    );

    return () => {
      listener?.subscription.unsubscribe();
    };
  }, []);

  return (
    <Page>
      <Head>
        <title>TasteNotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <header className="flex justify-center m-20">
          <div className="flex flex-col text-center gap-6">
            <Image
              src="/ramune.png"
              alt="TasteNotes logo"
              width={200}
              height={200}
            />
            <h1 className="text-4xl font-bold">TasteNotes</h1>
          </div>
        </header>
      </main>
    </Page>
  );
}
