mutation CreateTreat(
  $name: String!
  $companyId: ID!
  $categoryId: ID!
  $subcategoryId: ID!
) {
  createTreat(
    name: $name
    companyId: $companyId
    categoryId: $categoryId
    subcategoryId: $subcategoryId
  ) {
    id
  }
}

mutation CreateSubcategory($name: String!, $categoryId: ID!) {
  createSubcategory(name: $name, categoryId: $categoryId) {
    id
  }
}

query SubcategoriesByCategory($categoryId: ID!) {
  subcategoriesByCategory(categoryId: $categoryId) {
    id
    name
  }
}

query Companies {
  companies {
    id
    name
  }
}

mutation CreateCategory($name: String!) {
  createCategory(name: $name) {
    id
  }
}

mutation CreateCompany($name: String!) {
  createCompany(name: $name) {
    id
  }
}

query Categories {
  categories {
    id
    name
    subcategories {
      id
      name
    }
  }
}
