opt_in_rules:
  - force_unwrapping
  - empty_count
  - trailing_newline
  - colon
  - comma
  - duplicate_imports
  - fatal_error_message
  - first_where
  - weak_delegate
  - void_return
  - fallthrough
  - yoda_condition
  - sorted_imports
  - sorted_first_last
  - identical_operands
  - file_name_no_space
  - empty_string
  - discouraged_none_name
  - contains_over_first_not_nil
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - implicit_return
  - implicitly_unwrapped_optional
  - redundant_type_annotation
  - private_over_fileprivate
  - redundant_nil_coalescing
disabled_rules:
  - trailing_comma
  - function_body_length
  - opening_brace
  - nesting
  - cyclomatic_complexity
  - legacy_random
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 800
type_name:
  min_length: 3
identifier_name:
  max_length:
    warning: 45
    error: 50
  min_length:
    warning: 2
custom_rules:
  DynamicProperty_private:
    name: "Private SwiftUI DynamicProperty"
    regex: "@(AccessibilityFocusState|AppStorage|EnvironmentObject|FocusedObject|FocusedObject|GestureState|Namespace|ScaledMetric|SceneStorage|State|StateObject)\\s*?\\n?(\\s|\\t)*?(var|public|internal|open)"
    message: "SwiftUI DynamicProperty variables should always be marked private."
    severity: warning
  DynamicProperty_private_argument:
    name: "Private SwiftUI DynamicProperty"
    regex: "@(Environment|FetchRequest|FocusedValue|GestureState|NSApplicationDelegateAdaptor|ScaledMetric|SectionedFetchRequest)\\(.*\\)\\s*?\\n?(\\s|\\t)*?(var|public|internal|open)"
    message: "SwiftUI DynamicProperty(with argument) variables should always be marked private."
    severity: warning

private_over_fileprivate:
  validate_extensions: true
  severity: error
