opt_in_rules:
  - force_unwrapping
  - empty_count
disabled_rules:
  - trailing_comma
  - identifier_name
  - closure_parameter_position
  - function_body_length
  - todo
  - multiple_closures_with_trailing_closure
  - opening_brace
  - nesting
  - cyclomatic_complexity
  - legacy_random
  - notification_center_detachment
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 800