opt_in_rules:
  - force_unwrapping
  - empty_count
  - trailing_newline
  - colon
  - comma
  - duplicate_imports
  - fatal_error_message
  - first_where
  - weak_delegate
  - void_return
  - fallthrough
  - yoda_condition
  - sorted_imports
  - sorted_first_last
  - identical_operands
  - file_name_no_space
  - empty_string
  - discouraged_optional_collection
  - discouraged_none_name
  - contains_over_first_not_nil
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - implicit_return
  - implicitly_unwrapped_optional
disabled_rules:
  - trailing_comma
  - closure_parameter_position
  - function_body_length
  - todo
  - multiple_closures_with_trailing_closure
  - opening_brace
  - nesting
  - cyclomatic_complexity
  - legacy_random
  - notification_center_detachment
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 800
type_name:
  min_length: 3
identifier_name:
  max_length:
    warning: 45
    error: 50
  min_length:
    warning: 2
