opt_in_rules:
  - force_unwrapping
disabled_rules:
  - trailing_comma
  - identifier_name
  - closure_parameter_position
  - function_body_length
  - todo
  - multiple_closures_with_trailing_closure
  - opening_brace
  - nesting
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - legacy_random
  - notification_center_detachment
