-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE EXTENSION IF NOT EXISTS citext;

DROP TABLE IF EXISTS public.reactions CASCADE;

ALTER TABLE IF EXISTS public.products
    DROP COLUMN IF EXISTS manufacturer_id;

ALTER TABLE IF EXISTS public.products
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.products
    DROP CONSTRAINT IF EXISTS products_manufacturer_id_fkey;

REVOKE ALL ON TABLE public.companies FROM authenticated;

REVOKE ALL ON TABLE public.companies FROM postgres;

REVOKE ALL ON TABLE public.companies FROM service_role;

GRANT ALL ON TABLE public.companies TO authenticated;

GRANT ALL ON TABLE public.companies TO service_role;

GRANT ALL ON TABLE public.companies TO postgres;

ALTER TABLE IF EXISTS public.companies
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.companies
    ALTER COLUMN name SET STORAGE EXTENDED;

REVOKE ALL ON TABLE public.check_in_comments FROM authenticated;

REVOKE ALL ON TABLE public.check_in_comments FROM postgres;

REVOKE ALL ON TABLE public.check_in_comments FROM service_role;

GRANT ALL ON TABLE public.check_in_comments TO authenticated;

GRANT ALL ON TABLE public.check_in_comments TO service_role;

GRANT ALL ON TABLE public.check_in_comments TO postgres;

ALTER TABLE IF EXISTS public.check_in_comments
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.products_subcategories
    ALTER COLUMN product_id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.locations
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.categories
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

REVOKE ALL ON TABLE public.profiles FROM authenticated;

REVOKE ALL ON TABLE public.profiles FROM postgres;

REVOKE ALL ON TABLE public.profiles FROM service_role;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO service_role;

GRANT ALL ON TABLE public.profiles TO postgres;

ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT check_username CHECK (length(username) >= 2 AND length(username) <= 24 AND username ~ '^[a-zA-Z]([_.]?[a-zA-Z0-9])+$'::citext::text);

REVOKE ALL ON TABLE public.check_in_tagged_profiles FROM authenticated;

REVOKE ALL ON TABLE public.check_in_tagged_profiles FROM postgres;

REVOKE ALL ON TABLE public.check_in_tagged_profiles FROM service_role;

GRANT ALL ON TABLE public.check_in_tagged_profiles TO authenticated;

GRANT ALL ON TABLE public.check_in_tagged_profiles TO service_role;

GRANT ALL ON TABLE public.check_in_tagged_profiles TO postgres;

ALTER TABLE IF EXISTS public.check_in_reactions
    DROP COLUMN IF EXISTS reaction_id;

ALTER TABLE IF EXISTS public.check_in_reactions
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.check_in_reactions
    DROP CONSTRAINT IF EXISTS check_in_reactions_reaction_id_fkey;

ALTER TABLE IF EXISTS public.brands
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.brands
    ALTER COLUMN name SET STORAGE EXTENDED;

REVOKE ALL ON TABLE public.serving_styles FROM authenticated;

REVOKE ALL ON TABLE public.serving_styles FROM postgres;

REVOKE ALL ON TABLE public.serving_styles FROM service_role;

GRANT ALL ON TABLE public.serving_styles TO authenticated;

GRANT ALL ON TABLE public.serving_styles TO service_role;

GRANT ALL ON TABLE public.serving_styles TO postgres;

ALTER TABLE IF EXISTS public.serving_styles
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.check_ins
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

ALTER TABLE IF EXISTS public.subcategories
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET
    MINVALUE 1 SET
    MAXVALUE 2147483647 SET
    CACHE 1;

-- Type: reactions
-- DROP TYPE IF EXISTS public.reactions;
CREATE TYPE public.reactions AS ENUM (
    'toast',
    'like',
    'dislike',
    'love',
    'hate'
);

ALTER TYPE public.reactions OWNER TO postgres;

DROP VIEW IF EXISTS public.csv_export;

