-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict do nothing;

create policy "Allow deleting own avatar"
on storage.objects for delete
using ( auth.uid() = owner );

create policy "Allow updating own avatar"
on storage.objects for update
using ( auth.uid() = owner );