-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.subcategories FROM anon;
REVOKE ALL ON TABLE public.subcategories FROM postgres;
REVOKE ALL ON TABLE public.subcategories FROM service_role;
GRANT ALL ON TABLE public.subcategories TO anon;

GRANT ALL ON TABLE public.subcategories TO service_role;

GRANT ALL ON TABLE public.subcategories TO postgres;

REVOKE ALL ON TABLE public.product_variants FROM authenticated;
REVOKE ALL ON TABLE public.product_variants FROM postgres;
REVOKE ALL ON TABLE public.product_variants FROM service_role;
GRANT ALL ON TABLE public.product_variants TO authenticated;

GRANT ALL ON TABLE public.product_variants TO service_role;

GRANT ALL ON TABLE public.product_variants TO postgres;

REVOKE ALL ON TABLE public.friends FROM authenticated;
REVOKE ALL ON TABLE public.friends FROM postgres;
REVOKE ALL ON TABLE public.friends FROM service_role;
GRANT ALL ON TABLE public.friends TO authenticated;

GRANT ALL ON TABLE public.friends TO service_role;

GRANT ALL ON TABLE public.friends TO postgres;

REVOKE ALL ON TABLE public.check_in_reactions FROM anon;
REVOKE ALL ON TABLE public.check_in_reactions FROM postgres;
REVOKE ALL ON TABLE public.check_in_reactions FROM service_role;
GRANT ALL ON TABLE public.check_in_reactions TO anon;

GRANT ALL ON TABLE public.check_in_reactions TO service_role;

GRANT ALL ON TABLE public.check_in_reactions TO postgres;

REVOKE ALL ON TABLE public.products_subcategories FROM anon;
REVOKE ALL ON TABLE public.products_subcategories FROM postgres;
REVOKE ALL ON TABLE public.products_subcategories FROM service_role;
GRANT ALL ON TABLE public.products_subcategories TO anon;

GRANT ALL ON TABLE public.products_subcategories TO service_role;

GRANT ALL ON TABLE public.products_subcategories TO postgres;

REVOKE ALL ON TABLE public.brands FROM anon;
REVOKE ALL ON TABLE public.brands FROM postgres;
REVOKE ALL ON TABLE public.brands FROM service_role;
GRANT ALL ON TABLE public.brands TO anon;

GRANT ALL ON TABLE public.brands TO service_role;

GRANT ALL ON TABLE public.brands TO postgres;

REVOKE ALL ON TABLE public.products FROM anon;
REVOKE ALL ON TABLE public.products FROM postgres;
REVOKE ALL ON TABLE public.products FROM service_role;
GRANT ALL ON TABLE public.products TO anon;

GRANT ALL ON TABLE public.products TO service_role;

GRANT ALL ON TABLE public.products TO postgres;

REVOKE ALL ON TABLE public.check_ins FROM anon;
REVOKE ALL ON TABLE public.check_ins FROM postgres;
REVOKE ALL ON TABLE public.check_ins FROM service_role;
GRANT ALL ON TABLE public.check_ins TO service_role;

GRANT ALL ON TABLE public.check_ins TO anon;

GRANT ALL ON TABLE public.check_ins TO postgres;

REVOKE ALL ON TABLE public.sub_brands FROM anon;
REVOKE ALL ON TABLE public.sub_brands FROM postgres;
REVOKE ALL ON TABLE public.sub_brands FROM service_role;
GRANT ALL ON TABLE public.sub_brands TO anon;

GRANT ALL ON TABLE public.sub_brands TO service_role;

GRANT ALL ON TABLE public.sub_brands TO postgres;
