-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.tg__set_avatar_on_upload()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF SECURITY DEFINER
    SET search_path=public
AS $BODY$
begin
  delete from storage.objects where name = new.name;
  update public.profiles set avatar_url = new.name where id = auth.uid();
  return new;
end;
$BODY$;

ALTER FUNCTION public.tg__set_avatar_on_upload()
    OWNER TO supabase_admin;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO anon;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO postgres;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO supabase_admin;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO authenticated;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO service_role;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO PUBLIC;

REVOKE ALL ON TABLE public.locations FROM authenticated;
REVOKE ALL ON TABLE public.locations FROM postgres;
REVOKE ALL ON TABLE public.locations FROM service_role;
GRANT ALL ON TABLE public.locations TO authenticated;

GRANT ALL ON TABLE public.locations TO postgres;

GRANT ALL ON TABLE public.locations TO service_role;

REVOKE ALL ON TABLE public.products_subcategories FROM authenticated;
REVOKE ALL ON TABLE public.products_subcategories FROM postgres;
REVOKE ALL ON TABLE public.products_subcategories FROM service_role;
GRANT ALL ON TABLE public.products_subcategories TO authenticated;

GRANT ALL ON TABLE public.products_subcategories TO service_role;

GRANT ALL ON TABLE public.products_subcategories TO postgres;

REVOKE ALL ON TABLE public.subcategories FROM authenticated;
REVOKE ALL ON TABLE public.subcategories FROM postgres;
REVOKE ALL ON TABLE public.subcategories FROM service_role;
GRANT ALL ON TABLE public.subcategories TO authenticated;

GRANT ALL ON TABLE public.subcategories TO service_role;

GRANT ALL ON TABLE public.subcategories TO postgres;

REVOKE ALL ON TABLE public.roles FROM authenticated;
REVOKE ALL ON TABLE public.roles FROM postgres;
REVOKE ALL ON TABLE public.roles FROM service_role;
GRANT ALL ON TABLE public.roles TO authenticated;

GRANT ALL ON TABLE public.roles TO postgres;

GRANT ALL ON TABLE public.roles TO service_role;

REVOKE ALL ON TABLE public.check_ins FROM authenticated;
REVOKE ALL ON TABLE public.check_ins FROM postgres;
REVOKE ALL ON TABLE public.check_ins FROM service_role;
GRANT ALL ON TABLE public.check_ins TO authenticated;

GRANT ALL ON TABLE public.check_ins TO service_role;

GRANT ALL ON TABLE public.check_ins TO postgres;

REVOKE ALL ON TABLE public.categories FROM authenticated;
REVOKE ALL ON TABLE public.categories FROM postgres;
REVOKE ALL ON TABLE public.categories FROM service_role;
GRANT ALL ON TABLE public.categories TO authenticated;

GRANT ALL ON TABLE public.categories TO postgres;

GRANT ALL ON TABLE public.categories TO service_role;

REVOKE ALL ON TABLE public.check_in_flavors FROM authenticated;
REVOKE ALL ON TABLE public.check_in_flavors FROM postgres;
REVOKE ALL ON TABLE public.check_in_flavors FROM service_role;
GRANT ALL ON TABLE public.check_in_flavors TO authenticated;

GRANT ALL ON TABLE public.check_in_flavors TO postgres;

GRANT ALL ON TABLE public.check_in_flavors TO service_role;

REVOKE ALL ON TABLE public.profiles FROM anon;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO service_role;

GRANT ALL ON TABLE public.profiles TO postgres;

REVOKE ALL ON TABLE public."sub-brands" FROM authenticated;
REVOKE ALL ON TABLE public."sub-brands" FROM postgres;
REVOKE ALL ON TABLE public."sub-brands" FROM service_role;
GRANT ALL ON TABLE public."sub-brands" TO authenticated;

GRANT ALL ON TABLE public."sub-brands" TO service_role;

GRANT ALL ON TABLE public."sub-brands" TO postgres;

REVOKE ALL ON TABLE public.check_in_tagged_profiles FROM anon;
REVOKE ALL ON TABLE public.check_in_tagged_profiles FROM postgres;
REVOKE ALL ON TABLE public.check_in_tagged_profiles FROM service_role;
GRANT ALL ON TABLE public.check_in_tagged_profiles TO postgres;

GRANT ALL ON TABLE public.check_in_tagged_profiles TO anon;

GRANT ALL ON TABLE public.check_in_tagged_profiles TO service_role;

REVOKE ALL ON TABLE public.products FROM authenticated;
REVOKE ALL ON TABLE public.products FROM postgres;
REVOKE ALL ON TABLE public.products FROM service_role;
GRANT ALL ON TABLE public.products TO authenticated;

GRANT ALL ON TABLE public.products TO service_role;

GRANT ALL ON TABLE public.products TO postgres;

REVOKE ALL ON TABLE public.user_roles FROM authenticated;
REVOKE ALL ON TABLE public.user_roles FROM postgres;
REVOKE ALL ON TABLE public.user_roles FROM service_role;
GRANT ALL ON TABLE public.user_roles TO authenticated;

GRANT ALL ON TABLE public.user_roles TO postgres;

GRANT ALL ON TABLE public.user_roles TO service_role;

REVOKE ALL ON TABLE public.flavors FROM authenticated;
REVOKE ALL ON TABLE public.flavors FROM postgres;
REVOKE ALL ON TABLE public.flavors FROM service_role;
GRANT ALL ON TABLE public.flavors TO authenticated;

GRANT ALL ON TABLE public.flavors TO postgres;

GRANT ALL ON TABLE public.flavors TO service_role;

REVOKE ALL ON TABLE public.check_in_reactions FROM authenticated;
REVOKE ALL ON TABLE public.check_in_reactions FROM postgres;
REVOKE ALL ON TABLE public.check_in_reactions FROM service_role;
GRANT ALL ON TABLE public.check_in_reactions TO authenticated;

GRANT ALL ON TABLE public.check_in_reactions TO service_role;

GRANT ALL ON TABLE public.check_in_reactions TO postgres;

REVOKE ALL ON TABLE public.migration_table FROM authenticated;
REVOKE ALL ON TABLE public.migration_table FROM postgres;
REVOKE ALL ON TABLE public.migration_table FROM service_role;
GRANT ALL ON TABLE public.migration_table TO authenticated;

GRANT ALL ON TABLE public.migration_table TO postgres;

GRANT ALL ON TABLE public.migration_table TO service_role;

REVOKE ALL ON TABLE public.check_in_comments FROM anon;
REVOKE ALL ON TABLE public.check_in_comments FROM postgres;
REVOKE ALL ON TABLE public.check_in_comments FROM service_role;
GRANT ALL ON TABLE public.check_in_comments TO postgres;

GRANT ALL ON TABLE public.check_in_comments TO anon;

GRANT ALL ON TABLE public.check_in_comments TO service_role;

REVOKE ALL ON TABLE public.serving_styles FROM anon;
REVOKE ALL ON TABLE public.serving_styles FROM postgres;
REVOKE ALL ON TABLE public.serving_styles FROM service_role;
GRANT ALL ON TABLE public.serving_styles TO postgres;

GRANT ALL ON TABLE public.serving_styles TO anon;

GRANT ALL ON TABLE public.serving_styles TO service_role;

REVOKE ALL ON TABLE public.companies FROM anon;
REVOKE ALL ON TABLE public.companies FROM postgres;
REVOKE ALL ON TABLE public.companies FROM service_role;
GRANT ALL ON TABLE public.companies TO postgres;

GRANT ALL ON TABLE public.companies TO anon;

GRANT ALL ON TABLE public.companies TO service_role;

REVOKE ALL ON TABLE public.friends FROM authenticated;
REVOKE ALL ON TABLE public.friends FROM postgres;
REVOKE ALL ON TABLE public.friends FROM service_role;
GRANT ALL ON TABLE public.friends TO authenticated;

GRANT ALL ON TABLE public.friends TO service_role;

GRANT ALL ON TABLE public.friends TO postgres;

REVOKE ALL ON TABLE public.brands FROM authenticated;
REVOKE ALL ON TABLE public.brands FROM postgres;
REVOKE ALL ON TABLE public.brands FROM service_role;
GRANT ALL ON TABLE public.brands TO authenticated;

GRANT ALL ON TABLE public.brands TO service_role;

GRANT ALL ON TABLE public.brands TO postgres;
