-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP EXTENSION IF EXISTS pg_graphql;

CREATE OR REPLACE FUNCTION public.tg__set_check_in_image_on_upload()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
    SET search_path=public
AS $BODY$
begin
  if new.bucket_id = 'check-ins' then
    with parts as (select string_to_array(new.name, '/') arr),
         formatted_parts as (select array_to_string(arr[2:], '')                      image_url,
                                    substr(array_to_string(arr[2:], ''), 0,
                                           strpos(array_to_string(arr[2:], ''), '.'))::bigint check_in_id
                             from parts)
    update
      check_ins
    set image_url = fp.image_url
    from formatted_parts fp
    where created_by = new.owner
      and id = fp.check_in_id;
  end if;
  return new;
end;
$BODY$;

GRANT EXECUTE ON FUNCTION public.tg__set_check_in_image_on_upload() TO authenticated;

GRANT EXECUTE ON FUNCTION public.tg__set_check_in_image_on_upload() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.tg__set_check_in_image_on_upload() TO postgres;

GRANT EXECUTE ON FUNCTION public.tg__set_check_in_image_on_upload() TO anon;

GRANT EXECUTE ON FUNCTION public.tg__set_check_in_image_on_upload() TO service_role;

CREATE OR REPLACE FUNCTION public.tg__set_avatar_on_upload()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    VOLATILE SECURITY DEFINER
    COST 100
AS $BODY$
begin
  if new.bucket_id = 'avatars' then
    delete from storage.objects where name = new.name;
    update public.profiles set avatar_url = new.name where id = auth.uid();
  end if;
  return new;
end;
$BODY$;

REVOKE ALL ON FUNCTION public.tg__set_avatar_on_upload() FROM postgres;

REVOKE ALL ON FUNCTION public.tg__set_avatar_on_upload() FROM supabase_admin;

REVOKE ALL ON FUNCTION public.tg__set_avatar_on_upload() FROM authenticated;

REVOKE ALL ON FUNCTION public.tg__set_avatar_on_upload() FROM PUBLIC;

REVOKE ALL ON FUNCTION public.tg__set_avatar_on_upload() FROM service_role;

GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO authenticated;


GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO PUBLIC;


GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO postgres;


GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO anon;


GRANT EXECUTE ON FUNCTION public.tg__set_avatar_on_upload() TO service_role;