-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.fnc__export_data()
    RETURNS SETOF csv_export
    LANGUAGE 'plpgsql'
    VOLATILE
    PARALLEL UNSAFE
    COST 100    ROWS 1000 
    
AS $BODY$
begin
    return query (select * from csv_export
                  where id = auth.uid());
end;
$BODY$;

DROP TABLE IF EXISTS public."sub-brands" CASCADE;

REVOKE ALL ON TABLE public.check_in_reactions FROM authenticated;
REVOKE ALL ON TABLE public.check_in_reactions FROM postgres;
REVOKE ALL ON TABLE public.check_in_reactions FROM service_role;
GRANT ALL ON TABLE public.check_in_reactions TO authenticated;

GRANT ALL ON TABLE public.check_in_reactions TO service_role;

GRANT ALL ON TABLE public.check_in_reactions TO postgres;

REVOKE ALL ON TABLE public.check_ins FROM anon;
REVOKE ALL ON TABLE public.check_ins FROM authenticated;
REVOKE ALL ON TABLE public.check_ins FROM postgres;
REVOKE ALL ON TABLE public.check_ins FROM service_role;
GRANT ALL ON TABLE public.check_ins TO service_role;

GRANT ALL ON TABLE public.check_ins TO authenticated;

GRANT ALL ON TABLE public.check_ins TO anon;

GRANT ALL ON TABLE public.check_ins TO postgres;

REVOKE ALL ON TABLE public.brands FROM authenticated;
REVOKE ALL ON TABLE public.brands FROM postgres;
REVOKE ALL ON TABLE public.brands FROM service_role;
GRANT ALL ON TABLE public.brands TO authenticated;

GRANT ALL ON TABLE public.brands TO service_role;

GRANT ALL ON TABLE public.brands TO postgres;

REVOKE ALL ON TABLE public.sub_brands FROM authenticated;
REVOKE ALL ON TABLE public.sub_brands FROM service_role;
REVOKE ALL ON TABLE public.sub_brands FROM postgres;
GRANT ALL ON TABLE public.sub_brands TO authenticated;

GRANT ALL ON TABLE public.sub_brands TO postgres;

GRANT ALL ON TABLE public.sub_brands TO service_role;

REVOKE ALL ON TABLE public.friends FROM anon;
REVOKE ALL ON TABLE public.friends FROM postgres;
REVOKE ALL ON TABLE public.friends FROM service_role;
GRANT ALL ON TABLE public.friends TO anon;

GRANT ALL ON TABLE public.friends TO service_role;

GRANT ALL ON TABLE public.friends TO postgres;
