/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/brands": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.brands.id"];
          name?: parameters["rowFilter.brands.name"];
          brand_owner_id?: parameters["rowFilter.brands.brand_owner_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["brands"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** brands */
          brands?: definitions["brands"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.brands.id"];
          name?: parameters["rowFilter.brands.name"];
          brand_owner_id?: parameters["rowFilter.brands.brand_owner_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.brands.id"];
          name?: parameters["rowFilter.brands.name"];
          brand_owner_id?: parameters["rowFilter.brands.brand_owner_id"];
        };
        body: {
          /** brands */
          brands?: definitions["brands"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/categories": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.categories.id"];
          name?: parameters["rowFilter.categories.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["categories"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** categories */
          categories?: definitions["categories"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.categories.id"];
          name?: parameters["rowFilter.categories.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.categories.id"];
          name?: parameters["rowFilter.categories.name"];
        };
        body: {
          /** categories */
          categories?: definitions["categories"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/check_ins": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.check_ins.id"];
          rating?: parameters["rowFilter.check_ins.rating"];
          review?: parameters["rowFilter.check_ins.review"];
          author_id?: parameters["rowFilter.check_ins.author_id"];
          product_id?: parameters["rowFilter.check_ins.product_id"];
          check_in_date?: parameters["rowFilter.check_ins.check_in_date"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["check_ins"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** check_ins */
          check_ins?: definitions["check_ins"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.check_ins.id"];
          rating?: parameters["rowFilter.check_ins.rating"];
          review?: parameters["rowFilter.check_ins.review"];
          author_id?: parameters["rowFilter.check_ins.author_id"];
          product_id?: parameters["rowFilter.check_ins.product_id"];
          check_in_date?: parameters["rowFilter.check_ins.check_in_date"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.check_ins.id"];
          rating?: parameters["rowFilter.check_ins.rating"];
          review?: parameters["rowFilter.check_ins.review"];
          author_id?: parameters["rowFilter.check_ins.author_id"];
          product_id?: parameters["rowFilter.check_ins.product_id"];
          check_in_date?: parameters["rowFilter.check_ins.check_in_date"];
        };
        body: {
          /** check_ins */
          check_ins?: definitions["check_ins"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/companies": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.companies.id"];
          name?: parameters["rowFilter.companies.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["companies"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** companies */
          companies?: definitions["companies"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.companies.id"];
          name?: parameters["rowFilter.companies.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.companies.id"];
          name?: parameters["rowFilter.companies.name"];
        };
        body: {
          /** companies */
          companies?: definitions["companies"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/csv": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.csv.id"];
          category?: parameters["rowFilter.csv.category"];
          subcategory?: parameters["rowFilter.csv.subcategory"];
          manufacturer?: parameters["rowFilter.csv.manufacturer"];
          brand_owner?: parameters["rowFilter.csv.brand_owner"];
          Brand?: parameters["rowFilter.csv.Brand"];
          "sub-brand"?: parameters["rowFilter.csv.sub-brand"];
          flavour?: parameters["rowFilter.csv.flavour"];
          description?: parameters["rowFilter.csv.description"];
          rating?: parameters["rowFilter.csv.rating"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["csv"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** csv */
          csv?: definitions["csv"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.csv.id"];
          category?: parameters["rowFilter.csv.category"];
          subcategory?: parameters["rowFilter.csv.subcategory"];
          manufacturer?: parameters["rowFilter.csv.manufacturer"];
          brand_owner?: parameters["rowFilter.csv.brand_owner"];
          Brand?: parameters["rowFilter.csv.Brand"];
          "sub-brand"?: parameters["rowFilter.csv.sub-brand"];
          flavour?: parameters["rowFilter.csv.flavour"];
          description?: parameters["rowFilter.csv.description"];
          rating?: parameters["rowFilter.csv.rating"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.csv.id"];
          category?: parameters["rowFilter.csv.category"];
          subcategory?: parameters["rowFilter.csv.subcategory"];
          manufacturer?: parameters["rowFilter.csv.manufacturer"];
          brand_owner?: parameters["rowFilter.csv.brand_owner"];
          Brand?: parameters["rowFilter.csv.Brand"];
          "sub-brand"?: parameters["rowFilter.csv.sub-brand"];
          flavour?: parameters["rowFilter.csv.flavour"];
          description?: parameters["rowFilter.csv.description"];
          rating?: parameters["rowFilter.csv.rating"];
        };
        body: {
          /** csv */
          csv?: definitions["csv"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/materialized_overview": {
    get: {
      parameters: {
        query: {
          category?: parameters["rowFilter.materialized_overview.category"];
          subcategory?: parameters["rowFilter.materialized_overview.subcategory"];
          manufacturer?: parameters["rowFilter.materialized_overview.manufacturer"];
          brand_owner?: parameters["rowFilter.materialized_overview.brand_owner"];
          brand?: parameters["rowFilter.materialized_overview.brand"];
          "sub-brand"?: parameters["rowFilter.materialized_overview.sub-brand"];
          name?: parameters["rowFilter.materialized_overview.name"];
          description?: parameters["rowFilter.materialized_overview.description"];
          rating?: parameters["rowFilter.materialized_overview.rating"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["materialized_overview"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
  };
  "/overview": {
    get: {
      parameters: {
        query: {
          category?: parameters["rowFilter.overview.category"];
          subcategory?: parameters["rowFilter.overview.subcategory"];
          manufacturer?: parameters["rowFilter.overview.manufacturer"];
          brand_owner?: parameters["rowFilter.overview.brand_owner"];
          brand?: parameters["rowFilter.overview.brand"];
          "sub-brand"?: parameters["rowFilter.overview.sub-brand"];
          name?: parameters["rowFilter.overview.name"];
          description?: parameters["rowFilter.overview.description"];
          rating?: parameters["rowFilter.overview.rating"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["overview"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          manufacturer_id?: parameters["rowFilter.products.manufacturer_id"];
          subcategory_id?: parameters["rowFilter.products.subcategory_id"];
          sub_brand_id?: parameters["rowFilter.products.sub_brand_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          manufacturer_id?: parameters["rowFilter.products.manufacturer_id"];
          subcategory_id?: parameters["rowFilter.products.subcategory_id"];
          sub_brand_id?: parameters["rowFilter.products.sub_brand_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          manufacturer_id?: parameters["rowFilter.products.manufacturer_id"];
          subcategory_id?: parameters["rowFilter.products.subcategory_id"];
          sub_brand_id?: parameters["rowFilter.products.sub_brand_id"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          first_name?: parameters["rowFilter.profiles.first_name"];
          last_name?: parameters["rowFilter.profiles.last_name"];
          username?: parameters["rowFilter.profiles.username"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          website?: parameters["rowFilter.profiles.website"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          first_name?: parameters["rowFilter.profiles.first_name"];
          last_name?: parameters["rowFilter.profiles.last_name"];
          username?: parameters["rowFilter.profiles.username"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          website?: parameters["rowFilter.profiles.website"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          first_name?: parameters["rowFilter.profiles.first_name"];
          last_name?: parameters["rowFilter.profiles.last_name"];
          username?: parameters["rowFilter.profiles.username"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          website?: parameters["rowFilter.profiles.website"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/sub_brands": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sub_brands.id"];
          name?: parameters["rowFilter.sub_brands.name"];
          brand_id?: parameters["rowFilter.sub_brands.brand_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["sub_brands"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** sub_brands */
          sub_brands?: definitions["sub_brands"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sub_brands.id"];
          name?: parameters["rowFilter.sub_brands.name"];
          brand_id?: parameters["rowFilter.sub_brands.brand_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sub_brands.id"];
          name?: parameters["rowFilter.sub_brands.name"];
          brand_id?: parameters["rowFilter.sub_brands.brand_id"];
        };
        body: {
          /** sub_brands */
          sub_brands?: definitions["sub_brands"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/subcategories": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subcategories.id"];
          name?: parameters["rowFilter.subcategories.name"];
          category_id?: parameters["rowFilter.subcategories.category_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["subcategories"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** subcategories */
          subcategories?: definitions["subcategories"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subcategories.id"];
          name?: parameters["rowFilter.subcategories.name"];
          category_id?: parameters["rowFilter.subcategories.category_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subcategories.id"];
          name?: parameters["rowFilter.subcategories.name"];
          category_id?: parameters["rowFilter.subcategories.category_id"];
        };
        body: {
          /** subcategories */
          subcategories?: definitions["subcategories"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  brands: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `companies.id`.<fk table='companies' column='id'/>
     */
    brand_owner_id?: number;
  };
  categories: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name: string;
  };
  check_ins: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: integer */
    rating?: number;
    /** Format: text */
    review?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    author_id: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `products.id`.<fk table='products' column='id'/>
     */
    product_id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    check_in_date?: string;
  };
  companies: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name: string;
  };
  csv: {
    /** Format: bigint */
    id?: number;
    /** Format: text */
    category?: string;
    /** Format: text */
    subcategory?: string;
    /** Format: text */
    manufacturer?: string;
    /** Format: text */
    brand_owner?: string;
    /** Format: text */
    Brand?: string;
    /** Format: text */
    "sub-brand"?: string;
    /** Format: text */
    flavour?: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    rating?: string;
  };
  materialized_overview: {
    /** Format: text */
    category?: string;
    /** Format: text */
    subcategory?: string;
    /** Format: text */
    manufacturer?: string;
    /** Format: text */
    brand_owner?: string;
    /** Format: text */
    brand?: string;
    /** Format: text */
    "sub-brand"?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    description?: string;
    /** Format: double precision */
    rating?: number;
  };
  overview: {
    /** Format: text */
    category?: string;
    /** Format: text */
    subcategory?: string;
    /** Format: text */
    manufacturer?: string;
    /** Format: text */
    brand_owner?: string;
    /** Format: text */
    brand?: string;
    /** Format: text */
    "sub-brand"?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    description?: string;
    /** Format: double precision */
    rating?: number;
  };
  products: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name: string;
    /** Format: text */
    description?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `companies.id`.<fk table='companies' column='id'/>
     */
    manufacturer_id?: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `subcategories.id`.<fk table='subcategories' column='id'/>
     */
    subcategory_id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `sub_brands.id`.<fk table='sub_brands' column='id'/>
     */
    sub_brand_id: number;
  };
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    first_name?: string;
    /** Format: text */
    last_name?: string;
    /** Format: text */
    username: string;
    /** Format: text */
    avatar_url?: string;
    /** Format: text */
    website?: string;
  };
  sub_brands: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `brands.id`.<fk table='brands' column='id'/>
     */
    brand_id?: number;
  };
  subcategories: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `categories.id`.<fk table='categories' column='id'/>
     */
    category_id: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description brands */
  "body.brands": definitions["brands"];
  /** Format: bigint */
  "rowFilter.brands.id": string;
  /** Format: text */
  "rowFilter.brands.name": string;
  /** Format: bigint */
  "rowFilter.brands.brand_owner_id": string;
  /** @description categories */
  "body.categories": definitions["categories"];
  /** Format: bigint */
  "rowFilter.categories.id": string;
  /** Format: text */
  "rowFilter.categories.name": string;
  /** @description check_ins */
  "body.check_ins": definitions["check_ins"];
  /** Format: bigint */
  "rowFilter.check_ins.id": string;
  /** Format: integer */
  "rowFilter.check_ins.rating": string;
  /** Format: text */
  "rowFilter.check_ins.review": string;
  /** Format: uuid */
  "rowFilter.check_ins.author_id": string;
  /** Format: bigint */
  "rowFilter.check_ins.product_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.check_ins.check_in_date": string;
  /** @description companies */
  "body.companies": definitions["companies"];
  /** Format: bigint */
  "rowFilter.companies.id": string;
  /** Format: text */
  "rowFilter.companies.name": string;
  /** @description csv */
  "body.csv": definitions["csv"];
  /** Format: bigint */
  "rowFilter.csv.id": string;
  /** Format: text */
  "rowFilter.csv.category": string;
  /** Format: text */
  "rowFilter.csv.subcategory": string;
  /** Format: text */
  "rowFilter.csv.manufacturer": string;
  /** Format: text */
  "rowFilter.csv.brand_owner": string;
  /** Format: text */
  "rowFilter.csv.Brand": string;
  /** Format: text */
  "rowFilter.csv.sub-brand": string;
  /** Format: text */
  "rowFilter.csv.flavour": string;
  /** Format: text */
  "rowFilter.csv.description": string;
  /** Format: text */
  "rowFilter.csv.rating": string;
  /** @description materialized_overview */
  "body.materialized_overview": definitions["materialized_overview"];
  /** Format: text */
  "rowFilter.materialized_overview.category": string;
  /** Format: text */
  "rowFilter.materialized_overview.subcategory": string;
  /** Format: text */
  "rowFilter.materialized_overview.manufacturer": string;
  /** Format: text */
  "rowFilter.materialized_overview.brand_owner": string;
  /** Format: text */
  "rowFilter.materialized_overview.brand": string;
  /** Format: text */
  "rowFilter.materialized_overview.sub-brand": string;
  /** Format: text */
  "rowFilter.materialized_overview.name": string;
  /** Format: text */
  "rowFilter.materialized_overview.description": string;
  /** Format: double precision */
  "rowFilter.materialized_overview.rating": string;
  /** @description overview */
  "body.overview": definitions["overview"];
  /** Format: text */
  "rowFilter.overview.category": string;
  /** Format: text */
  "rowFilter.overview.subcategory": string;
  /** Format: text */
  "rowFilter.overview.manufacturer": string;
  /** Format: text */
  "rowFilter.overview.brand_owner": string;
  /** Format: text */
  "rowFilter.overview.brand": string;
  /** Format: text */
  "rowFilter.overview.sub-brand": string;
  /** Format: text */
  "rowFilter.overview.name": string;
  /** Format: text */
  "rowFilter.overview.description": string;
  /** Format: double precision */
  "rowFilter.overview.rating": string;
  /** @description products */
  "body.products": definitions["products"];
  /** Format: bigint */
  "rowFilter.products.id": string;
  /** Format: text */
  "rowFilter.products.name": string;
  /** Format: text */
  "rowFilter.products.description": string;
  /** Format: bigint */
  "rowFilter.products.manufacturer_id": string;
  /** Format: bigint */
  "rowFilter.products.subcategory_id": string;
  /** Format: bigint */
  "rowFilter.products.sub_brand_id": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.updated_at": string;
  /** Format: text */
  "rowFilter.profiles.first_name": string;
  /** Format: text */
  "rowFilter.profiles.last_name": string;
  /** Format: text */
  "rowFilter.profiles.username": string;
  /** Format: text */
  "rowFilter.profiles.avatar_url": string;
  /** Format: text */
  "rowFilter.profiles.website": string;
  /** @description sub_brands */
  "body.sub_brands": definitions["sub_brands"];
  /** Format: bigint */
  "rowFilter.sub_brands.id": string;
  /** Format: text */
  "rowFilter.sub_brands.name": string;
  /** Format: bigint */
  "rowFilter.sub_brands.brand_id": string;
  /** @description subcategories */
  "body.subcategories": definitions["subcategories"];
  /** Format: bigint */
  "rowFilter.subcategories.id": string;
  /** Format: text */
  "rowFilter.subcategories.name": string;
  /** Format: bigint */
  "rowFilter.subcategories.category_id": string;
}

export interface operations {}

export interface external {}
